### ISSUE TITLE
Crash in USDZResolveAsset (rendermesh-refactor)

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#159] opened 2024-05-03 08:30 UTC
In rendermesh-refactor branch, we've got a crash in USDZResolveAsset on the following model
https://developer.apple.com/augmented-reality/quick-look/models/redchair/chair_swan.usdz

`  if (passet->asset_map.count(asset_path)) {`

The call stack is the following:

> std::_Tree<std::_Tmap_traits<std::string,std::pair<unsigned __int64,unsigned __int64>,std::less<std::string>,std::allocator<std::pair<std::string const ,std::pair<unsigned __int64,unsigned __int64>>>,0>>::_Find_lower_bound<std::string>(const std::string & _Keyval={...}) Line 1608	C++
> 
> std::_Tree<std::_Tmap_traits<std::string,std::pair<unsigned __int64,unsigned __int64>,std::less<std::string>,std::allocator<std::pair<std::string const ,std::pair<unsigned __int64,unsigned __int64>>>,0>>::count(const std::string & _Keyval={...}) Line 1405	C++
> 
> tinyusdz::USDZResolveAsset(const char * asset_name=0x000000001cceca90, const std::vector<std::string,std::allocator<std::string>> & search_paths={...}, std::string * resolved_asset_name=0x0000000000144068, std::string * err=0x00000000001440a8, void * userdata=0x0000000000145790) Line 1263	C++
> 
> USDIo.dll!tinyusdz::AssetResolutionResolver::find(const std::string & assetPath={...}) Line 43	C++
> 

We setup an asset resolver in the following way:

>     tinyusdz::AssetResolutionResolver arr;
>     ...
>     else if (fileGetExtension(reffilename).CompareNoCase(_T(".usdz")) == 0)
>     {
>         tinyusdz::USDZAsset usdz_asset;
>         
>         {
>             // Setup AssetResolutionResolver to read a asset(file) from memory. 
>             if (!tinyusdz::ReadUSDZAssetInfoFromFile(filename, &usdz_asset, &warn, &err)) 
>             {
>                 std::cerr << "Failed to read USDZ assetInfo from file: " << err << "\n";
>                 exit(-1);
>             }
>             if (warn.size()) {
>                 std::cout << warn << "\n";
>             }
> 
>             // NOTE: Pointer address of usdz_asset must be valid until the call of RenderSceneConverter::ConvertToRenderScene.
>             if (!tinyusdz::SetupUSDZAssetResolution(arr, &usdz_asset)) 
>             {
>                 std::cerr << "Failed to setup AssetResolution for USDZ asset\n";
>                 exit(-1);
>             };
>

**Comment by syoyo** [comment] 2024-05-03 13:03
You should post minimal & reproducible code.

`tydra_to_renderscene chair_swan.usdz` works fine on Linux.

Apparently usdz_asset object should be placed outside of if-else clause, otherwise the instance of usdz_asset is free'ed after exiting `else if` clause. 

```
// NOTE: Pointer address of usdz_asset must be valid until the call of RenderSceneConverter::ConvertToRenderScene.
```

**Comment by syoyo** [comment] 2024-05-11 23:05
Closing since minimal & reproducible code is not provided

**Closed as completed by syoyo** 2024-05-11 23:05 UTC
Labels: invalid
